"""Known multi-user TCP command names and concise field layouts."""

COMMAND_FIELDS: dict[str, tuple[str, ...]] = {
    "ADDBLACKLISTCALL": ("callsign",),
    "ADDSPOT": ("call", "timestamp", "freq_x100", "comment", "qsx_x100", "spotter", "is_worked"),
    "CHECKSUM": (
        "start_ts",
        "end_ts",
        "checksum",
        "contest",
        "my_call",
        "num_minutes",
        "resync_all",
        "rescore_requested",
    ),
    "CLOSEPORT": (),
    "CONFIRMED": ("start_ts", "end_ts", "checksum", "num_minutes"),
    "CONTESTNAME": ("station", "contest_name", "contest_subtype"),
    "CQFREQ": ("freq_x100",),
    "DELETEQS": ("start_ts", "station_name", "num_minutes"),
    "DELETESPOT": ("callsign", "freq_x100"),
    "DISCONNECT_ME": (),
    "ECHO": ("date", "time"),
    "ECHOREQ": ("date", "time"),
    "FILE": ("file_name", "contents_or_path_payload"),
    "FREQ": ("freq_x100",),
    "FREQMODE": ("freq_x100", "mode", "focus_back_flag"),
    "FUNCTIONKEY": ("radio_nr", "callsign", "key_num"),
    "IAM": ("station_number_text",),
    "LASTQAT": ("last_qso_ts",),
    "MASTER": ("master_station_name",),
    "PACKET": ("packet_text",),
    "PACKETSTRING": ("packet_or_telnet_command",),
    "PASSFREQ": ("freq_x100",),
    "QSO": ("old_timestamp", "contact_qso_string_43_fields"),
    "QSODELETE": ("callsign", "timestamp"),
    "QSONRS": ("contest_name", "qso_numbers_0_to_31"),
    "REEDITQSO": ("old_timestamp", "old_callsign", "contact_qso_string_43_fields"),
    "REJECTNR": ("old_number",),
    "REMOVECALLSTACKCALLSIGN": ("callsign",),
    "REQCONTESTNAME": ("station", "unused_token"),
    "REQCQFREQ": (),
    "REQPASSFREQ": (),
    "RESERVENR": ("reserved_serial", "freq_x100"),
    "RESETQSONRS": (),
    "RESYNCQSO": ("old_timestamp", "contact_qso_string_43_fields"),
    "SKED": (
        "guid",
        "contest",
        "subtype",
        "deleted",
        "time",
        "call",
        "freq",
        "mode",
        "origin_station",
        "comment",
    ),
    "SKEDD": (),
    "SKEDSYNC": (),
    "STACKCALL": ("contact_qso_string_43_fields",),
    "STACKANOTHERCALL": ("callsign",),
    "STATUS": (
        "pass_or_cq_freq_x100",
        "current_freq_x100",
        "is_running",
        "operator",
        "last10",
        "last100",
        "mode",
        "operator_category",
        "transmitter_category",
        "country_file_version_prefix",
        "app_version",
        "block_station",
        "block_band",
        "block_band_mode",
        "force_stop",
        "force_stop_cq_only",
        "is_run2",
    ),
    "STOPIAM": (),
    "TALK": ("message",),
    "TIME": ("utc_timestamp",),
    "WHOAREU": (),
    "XMIT": ("is_xmit", "function_key_caption", "is_remote_run2", "is_f1_pressed", "stop_current_local_tx"),
}

RECEIVER_SUPPORTED_NO_CURRENT_SENDER = ("REQCONTESTNAME", "SKEDSYNC", "WHOAREU")


def known_commands() -> tuple[str, ...]:
    return tuple(sorted(COMMAND_FIELDS))
